### ISSUE TITLE
Unable to open any database due to "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by RaaaaaaaaaY** [HPCToolkit/hpcviewer#101]
I encountered this problem when trying to run "hpcviewer <hpctoolkit-some-database>". The problem also exists when opening hpctoolkit-some-database  under hpcviewer's GUI.

![image](https://user-images.githubusercontent.com/56531226/111464283-85b5f400-875b-11eb-91b3-4c7297e9de28.png)
or
![image](https://user-images.githubusercontent.com/56531226/111465798-70da6000-875d-11eb-8810-459043494a86.png)
then
![image](https://user-images.githubusercontent.com/56531226/111465944-a0896800-875d-11eb-9fd3-58c7e03ef34b.png)

___________________________________________________________________________________________________________________________________
Error message:
![image](https://user-images.githubusercontent.com/56531226/111464134-5ef7bd80-875b-11eb-8007-7a753f87b0d2.png)

Content of hpcviewer.err: (line 8 and 11 could be relevent?)
![image](https://user-images.githubusercontent.com/56531226/111464500-cd3c8000-875b-11eb-83c1-fd7b47a33587.png)

Hpcviewer and java dependent is installed through Spack:
![image](https://user-images.githubusercontent.com/56531226/111464963-74211c00-875c-11eb-801a-993052cdde67.png)

GTK version:
![image](https://user-images.githubusercontent.com/56531226/111465122-aa5e9b80-875c-11eb-86f0-ab1e7032b31f.png)

**Comment by laksono** [comment]
H @RaaaaaaaaaY. Can you share the database with us? Just the experiment.xml file inside the database directory.
We may also need the log files which is located in ~/.hpctoolkit/hpcviewer/x86_64/hpcviewer.log.

**Comment by RaaaaaaaaaY** [comment]
Oh thats my bad. Hpcviewer is fine. The problem has nothing to do with hpcviewer but, it looks like some skewed env variables/packages have caused the hpcrun/prof to generate empty database. Unloading a bunch of packages fixed the problem. I thing this issue can be deleted
