### ISSUE TITLE
Need to stop annoying error message: There are x samples with invalid call-path ID

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer#24]
This error message is really annoying. We need to display only once, or somewhere without dialog box.

**Comment by jmellorcrummey** [comment]
@laksono 

Perhaps we can add a status line at the bottom of the display where we could write a message in red

Note: x out of y samples in this view have invalid call path ID and are not rendered

**Comment by laksono** [comment]
Fixed
