### ISSUE TITLE
hpctraceviewer, callers view, and selection

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#28]
@laksono When I switch to the caller's view, I have no selection. When I select an exclusive cost column and sort by it, it should scroll to the top of the sorted list when no selection is present or the selection is scrolled off the screen (meaning that the user does not care about it). It does not do this currently. Instead, I need to manually scroll to the top after I sort by a new column.

**Comment by laksono** [comment]
For scrolling automatically after sorting: 
- when there is a selected node : this is done automatically by SWT. 
- when there is no selected nodes: fixed in commit bc1a718faca5ecdb0828e6e0a96599bb3a21093c
