### ISSUE TITLE
hpcviewer view names

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#30]
@laksono 

I think that we should change the view names in hpcviewer to be consistent with what VTune uses these days. I think it is more intuitive for users to think of
- Top-down
- Bottom-up
- Flat

than

- Calling Context View
- Caller's View
- Flat View

I think we can also leave "View" off the name.

When we make this change, we need to change the documentation as well.

**Comment by laksono** [comment]
Fixed
