### ISSUE TITLE
hpcviewer is slow for analyzing openmp-parse profile data on Linux

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#31]
@laksono See the file les:bugs/slow.tgz

Using hpcviewer on les with java 1.8.0_60 to analyze measurement data from openmp-parse is surprisingly slow. hpcviewer takes ~18s to bring up the callers view from the CCT view.

Similarly,  switching the column selection from sorted order on inclusive costs to exclusive costs takes about 18s as well. Switching back is the same. On my laptop, switching the sorting column takes only a second or so.

Using VisualVM to profile the time shows only ms for the operation. Profiling memory shows that it allocates 54MB of new char[] data (starting from a baseline of 9MB), garbage collects at 64MB and then allocates again up to about 54MB before the operation completes.

What it it about the interface that makes it slow on Linux? The problem might have to do with the fact that there are ~9400 procedures in experiment.xml. It seems that it is re-synthesizing information about the procedure entries on the fly when they should already be present.

**Comment by laksono** [comment]
This should be fixed by using lazy content provider
