### ISSUE TITLE
<omp idle> is omitted when creating the flat view

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#36]
Leaving <omp idle> out of the flat view leads to costs that don't add. It must be included. Notice that in the figure below, 45.7% is attributed to metric "cycles:Sum (E)" for <unknown file> [libomp.so] but only .4% is accounted for.
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/3926112/40209314-15f18544-5a04-11e8-809c-ce2a10922e14.png">
Looking at the caller's view, we can see that <omp idle> accounts for 45.5% of metric "cycles:Sum (E)".

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/3926112/40209333-292b61c0-5a04-11e8-82aa-160ea575fa63.png">

**Comment by laksono** [comment]
Fixed in commit  c74eccd58ff0e102393a189a53f102cb3c1d07a9
