### ISSUE TITLE
hpcviewer column selector: omit checkbox for empty columns

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#62]
columns that are empty are marked "(empty)" in the column selector. this is good.

however, they still have a selector checkbox. I put a check in one, but it didn't display the empty column. it would be better for empty metrics to not to have checkbox since they can't be displayed.

**Comment by laksono** [comment]
I wish I can do it.
Unfortunately, Eclipse doesn't provide a clean solution for that. There is a workaround for it, but I would not suggest to adopt it.
See:

- https://www.eclipse.org/forums/index.php/t/170694/
- https://stackoverflow.com/questions/12674974/swt-check-table-disable-checkbox

**Comment by jmellorcrummey** [comment]
The information that Laksono provided show that this is a defect of Eclipse and we should just move on rather than trying to fix it. Sigh.
