### ISSUE TITLE
hpcviewer doesn't respect display settings for computed metrics

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#63]
For the GPU kernel metrics, the goal was to do the following
	e.g. for thread registers

       in hpcrun
		1) accumulate the sum of thread registers used by all kernel invocations in a context
		2) count kernel invocations

       in hpcviewer
		hide the accumulators (inclusive and exclusive) for thread registers
		display ONLY the (exclusive sum of thread registers)/(exclusive count of invocations)

First, the accumulators were marked as display exclusive-only. All accumulator metrics for GPU kernels should be invisible. I just checked in the fix.

Second, the GPU kernel metrics (THR_REG, FGP_MAX, …) weren’t marked properly for display. They were unmarked, which defaults to show. I marked them exclusive-only, but hpcviewer displays both anyway. I saw it pay attention to the display value for measured metrics, but apparently, it ignores them for computed metrics.

The fix in hpcrun (appropriately tagging both measured and computed metrics properly). However, the second item needs fixing in hpcviewer. (it must obey the display setting for computed metrics.)

**Comment by laksono** [comment]
Fixed in commit b8e1e92d7b9cb3ea0e58459862ce7299f72d494a
