### ISSUE TITLE
hpcviewer incorrectly computes bottom-up metrics wrong in certain cases

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#68]
Notice that in the figure below, the second line has 40% inclusive cycles attributed to an inlined context whereas the enclosing function only has 27% inclusive. The outer context should include the cost of the inlined file in this case. My guess is that the support not propagating out of an inlined contex does the right thing for inlined functions, but not inlined files.

<img width="481" alt="image001" src="https://user-images.githubusercontent.com/3926112/73992243-18a71c80-4914-11ea-9d85-a9d13fde57bc.png">

**Comment by laksono** [comment]
Yes, that's clearly a bug. 

Can you share the database?

**Comment by jmellorcrummey** [comment]
on nancy.cs.rice.edu:qs.tar

(sent from my phone)

**Comment by laksono** [comment]
hpcprof generates the same flat ID (30445) for the same inlined function from different contexts, which confuses the viewer as shown below.
``` 
<Procedure i="30445" n="<inline>" f="1" v="0"/> 
<Procedure i="30480" n="CycleTrackingGuts(MonteCarlo*, int, ParticleVault*, ParticleVault*)" v="0x74380"/>
<Procedure i="30867" n="MC_Load_Particle(MonteCarlo*, MC_Particle&, ParticleVault*, int)" v="0x7ad80"/>
. . .
<C i="66" s="30489" l="20" v="0">
  <PF i="67" s="30867" l="106" lm="30360" f="30445" n="30867">
    <Pr i="69" s="30445" l="94" lm="30360" f="30445" n="30445" a="1">
      <S i="70" s="30870" l="94">
. . .
<C i="56" s="31015" l="132" v="0">
  <PF i="57" s="30480" l="17" lm="30360" f="30479" n="30480">
    <Pr i="131" s="30445" l="94" lm="30360" f="30445" n="30445" a="1">
      <S i="132" s="30491" l="94">
```

**Comment by laksono** [comment]
It seems this bug has been there for a long time, but we have never noticed it.
We can reproduce the bug even without hpcstruct file:

- Profile AMG as usual: 
```
mpirun -np 1 hpcrun -e cycles  ./amg2006  -P 1 1 1  -r 16 16 16
```
- Generate the database without hpcstruct file:
```
hpcprof hpctoolkit-amg2006-measurements
```
- Run hpcviewer, and see some functions in `par_relax.c`, `par_interp.c` and `csr_matvec.c` from the flat view. The cost of executing `[I] inlined from hypre_smp_forloop.h: 35` is always the same for different contexts, which is `7.13e+12` (see the red rectangle).

![image](https://user-images.githubusercontent.com/8781032/74260552-5236a980-4cbf-11ea-9545-94db8aafaa3a.png)

- Remark that the flat ID of `[I] inlined from hypre_smp_forloop.h: 35` is all `442`
```
    <Procedure i="442" n="&lt;inline&gt;" f="1" v="0"/>
```

**Comment by laksono** [comment]
I found that it is much easier to fix this in hpcviewer than in hpcprof. The existing experiment.xml allows hpcviewer to reconstruct "double aliens" (like inline functions) and "single alien" (like inline macro). In the later case, hpcviewer will create "artificial flat-id" that is unique .

**Comment by jmellorcrummey** [comment]
resolved with changes to hpcprof in commit to hpctoolkit master 7cd3bfb36f968606bd9c127f0931299d040c3c6f
