### ISSUE TITLE
new hpctraceviewer fails on mac with QMCpack data

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#73]
@laksono 

I tried opening the new mac hpctraceviewer on qmcpack on 32 ranks, 32 threads per rank. The GUI doesn't seem to load the data successfully.

- The trace view shows the initial view
- There is no information in the status bar at the top of the trace pane
- The call stack display doesn't show anything. 
- The depth view doesn't work. 
- Moving to a deeper depth doesn't change the trace view.

Below is what I see:

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/3926112/75708741-060bd300-5c87-11ea-9ae1-282a041d2223.png">

**Comment by laksono** [comment]
How to reproduce the bug? It looks like there's a deadlock issue.
I opened QMCPack database 32 ranks each with 32 threads (but probably not the same database), it works just fine.

**Comment by laksono** [comment]
@jmellorcrummey : can you confirm if the latest version of hpcviewer fixed this issue?

**Comment by jmellorcrummey** [comment]
the new version resolves the problem. closing ...
