### ISSUE TITLE
mac hpcviewer has bad default column width for metric descriptions

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#74]
Below is what I see when I open the metric properties pane  for a GPU PC sampling experiment on a mac.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/3926112/75753963-751e1180-5cf1-11ea-8c0b-8f3d5a5ce4dd.png">

The column width for the description seems fine on Linux.

**Comment by laksono** [comment]
Fixed in commit 1e4e44c9dc0dd29d9ca26660e5a2a503c0d89db1
Since users can expand the dialog box, it would be better if Eclipse can automatically wrap the text (instead of manually wrapping it).
