### ISSUE TITLE
Hpcviewer does not show load-module id beside stacktrace function

### ISSUE THREAD

**Issue by aarontcopal2** [HPCToolkit/hpcviewer#79]
Hi @laksono ,

I think the hpcviewer scope section is not displaying the load-module id beside functions whose source-code is missing. But I am not able to see it in my examples. I am running hpcviewer Release 2020.04 and hpctoolkit on commit id : d35096895a82affddd1914aea215299a0e17b693

![image](https://user-images.githubusercontent.com/17940384/79035001-bf5fa180-7b7f-11ea-905e-91e784bcbe7a.png)

**Comment by laksono** [comment]
Fixed in commit 5621b1abf38b6e0053b5f46e18d71d3e45457fe7
