### ISSUE TITLE
load module tags added for placeholders

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#82]
With a spack install of hpctoolkit, which strips line map information from libhpcrun.so, GPU placeholders (and likely others) have the load module appended when displaying them in hpcviewer. This should not happen. I just observed this for the 2020.05 pre-release that is posted.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/3926112/82924661-42776400-9f42-11ea-9c08-32c4659d5b7f.png">

**Comment by jmellorcrummey** [comment]
This needs to be fixed for the release.

**Comment by laksono** [comment]
Strange. All <gpu*> place holders are included in "fake procedures" in the master branch (I committed the fix a few days ago).
Did you run the recent version of hpcprof? Can you show me the database (I just need the experiment.xml)

I tried on the master branch, all <gpu*> place holders are "fake procedures":

![image](https://user-images.githubusercontent.com/8781032/82926472-dba77a00-9f44-11ea-9b67-4bcb87226fcc.png)

**Comment by jmellorcrummey** [comment]
See image below for experiment.xml

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3926112/82927848-f0850d00-9f46-11ea-913c-dd21e54085e1.png">

**Comment by laksono** [comment]
Interesting. It's really a bug in the viewer.
Can you share the database so I can debug?

**Comment by jmellorcrummey** [comment]
no.

**Comment by laksono** [comment]
That's fine. I will try to install hpctoolkit via spack.

**Comment by jmellorcrummey** [comment]
FYI: I am reporting this problem for ppc64le.

**Comment by laksono** [comment]
Yes, I can reproduce this on llnl.cs. I'll take a look.

**Comment by jmellorcrummey** [comment]
corrected in 2020.05 version. wrong for 2020.04
