### ISSUE TITLE
Column titles for stats metrics

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#95]
When hpcviewer constructs titles for metric columns in the tree viewer, it uses the following template (note punctuation and spacing)

`NAME :DESCRIPTION`

Instead, it should use the following template:

`NAME - DESCRIPTION`

**Comment by laksono** [comment]
I think what you meant is the **tooltip**. If this is the case, yes I agree with it.

**Comment by jmellorcrummey** [comment]
Yes, I meant the tooltip label. Please fix.
