### ISSUE TITLE
hot paths display not hot child for a leaf

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#96]
when using the flame button to open a hot path, the title bar for the viewer displays "no hot child" if it reaches a leaf. when it is at a leaf, there are no children. it should not complain with the "no hot child" message for a leaf. for an interior node, the message is fine.

**Comment by laksono** [comment]
Your argument seems to make sense, I found it annoying to have this error message every time it reaches the leaf node.

**Comment by laksono** [comment]
Fixed in commit 3a6c65788115cc601801ff4f423f07549612d4cd
