### ISSUE TITLE
more types for metrics are needed

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#97]
there is a type HPCRUN_FMT_SHOW_EXCLUSIVE, which is used for the details of exclusive metrics describing a kernel. there should also be a type HPCRUN_FMT_HIDE_EXCLUSIVE that can potentially show only the exclusive, but it will start hidden.

perhaps we need to rethink the types to make them orthogonal

SHOW vs. HIDE
EXCLUSIVE_ONLY
PROCEDURE_ONLY (metrics such as GPU kernel info which should not be propagated to their enclosing procedure, they should be MOVED there)

**Comment by laksono** [comment]
This should be treated in hpcprof. 
hpcrun just needs to specify in the metric descriptor that the exclusive (or inclusive) metric is to be hidden. Then, hpcprof can set the attribute "Show" to be "0" (which means hide) for that exclusive (or inclusive) metric.

**Comment by laksono** [comment]
Move this issue to hpctoolkit issue https://github.com/HPCToolkit/hpctoolkit/issues/305 for better issue tracking.
