### ISSUE TITLE
hpcviewer exits without error message when missing dependency GTK2

### ISSUE THREAD

**Issue by Vinpasso** [HPCToolkit/hpcviewer#99]
When installing `hpcviewer` using e.g. `spack` users might expect it to work out of the box. However, `hpcviewer` and `hpctraceviewer` both need `libgtk2.0` in order to run. While this is generally not a problem the error message could be a little more specific when `libgtk2.0` is missing. Currently, both tools just seem to exit with exit code 13 and no further error message.
```
~$ hpcviewer hpctoolkit-bqcd-database-9293
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1e based on jdk8u222-b10)
Redirect standard error to /home/di67wun/.hpctoolkit/hpcviewer/x86_64/hpcviewer.log
Max memory  : 6144 MB
java version: 1.8.0_222
~$ echo $?
13
```
Something more along the lines of the error message when the `DISPLAY` environment variable is not set would be desirable:
```
~$ hpcviewer hpctoolkit-bqcd-database-9293
hpcviewer: error: DISPLAY variable is not set
````
Pretty much anything that gives the user a hint as to what is wrong would help. If this is not easy to implement perhaps a troubleshooting FAQ entry or a note in the package description might help.

Spack package version `hpcviewer-2020.07-r4wfzvohqev5d56umlx2iog77brv4w3o`

**Comment by laksono** [comment]
@Vinpasso Can you try the latest hpcviewer 2020.12 hpcviewer? 
You can download it at http://hpctoolkit.org/download.html

**Comment by Vinpasso** [comment]
I cannot reproduce this using the download you provided (which I guess is a good thing). In fact, the provided version of hpcviewer seems to run just fine even without having libgtk2.0 installed. I guess this issue can be closed?

**Comment by laksono** [comment]
The latest hpcviewer (2020.12) is built based on Eclipse 4.x, while the older hpcviewer (2020.07) is based on Eclipse 3.x
Eclipse 4.x requires GTK 3.20 or newer, while Eclipse 3.x requires GTK 2.x. 
This should resolve your problem but we have to sacrifice people using very old systems. I think we can close this issue.

Note: the recent Eclipse can run on newer Java (from Java 8 to 14, but not Java 15).

**Comment by Vinpasso** [comment]
Ok, thanks for the help
